### ISSUE TITLE
The associated script can not be loaded

### ISSUE THREAD

**Issue by my-and-mail** [xsolla/xsolla-unity-sdk#1]
Hello.
After importing the sdk files into a blank project can be seen on all objects that do not reference the scripts. In the console, no errors.

Screenshots: 
http://take.ms/Z8wjl
http://take.ms/ljFmR
etc

Unity 5.3.5f1, Unity 5.2.2f1

**Comment by ioKun** [comment]
Hello,

Thank you for creating an issue. It was our mistake, seems that .meta files have been lost in the latest update.
Please check it now, everything should work properly.
Our apologies for inconvenience.
